### PR TITLE
Removed Trial account screenshot

### PR DESCRIPTION
**Pull request by Vikramkulkarni01**

### CODE REVIEW

**Comment by MichaelCzcz** [comment]
Please resolve conflict. Always do a fetch+pull before pushing anything to production to prevent conflicts.

**Comment by Vikramkulkarni01** [comment]
Hi @MichaelCzcz , 

I have done as you suggested. Please check

**Comment by MichaelCzcz** [comment]
There are still conflicts:
image

Please use the "Resolve conflicts" button to use the web editor.

**Comment by Vikramkulkarni01** [comment]
Hi @MichaelCzcz , 

I resolved the conflict

**Pull request merged**
