### PR TITLE
Updated URL in AppGyver tutorials

### PR DESCRIPTION
**Pull request by heytombeck**

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Please update the tags (products -> software-product). Thank you.

**Comment by heytombeck** [comment]
@MichaelCzcz should this replace the existing tag or be an additional one?

**Comment by MichaelCzcz** [comment]
> @MichaelCzcz should this replace the existing tag or be an additional one?

Just replace the parts that say "products with "software-product".

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
"software-product" not "software-products"

**Pull request merged**
