### PR TITLE
fix #20415 && #20416

### LINKED ISSUE #20415: Create a Fiori Launchpad App
Tutorials: https://developers.sap.com/tutorials/sapui5-fiori-cf-create-project.html
--------------------------

Hello,

Just minor adjustment, but there are 2 new parameters in generator-easy-ui5 at this moment (step 1):

? What do you want to do? Create a new OpenUI5/SAPUI5 project                          [app]
? How do you want to name this project? products
? Which namespace do you want to use? tutorial
**? Do you want to enable the SAP Fiori elements flexible programming model? No**
? On which platform would you like to host the application? SAP Launchpad service
? Which view type do you want to use? XML
? Where should your UI5 libs be served from? Content delivery network (SAPUI5)
? Would you like to create a new directory for the project? Yes
? Would you like to add JavaScript code assist libraries to the project? Yes
**? Would you like to initialize a local git repository for the project? Yes**
? What name should be displayed on the Fiori Launchpad tile? Products

Thank you.

### PR DESCRIPTION
**Pull request by nicoschoenteich**

### CODE REVIEW

**Comment by nicoschoenteich** [comment]
Hi @MichaelCzcz, I have signed the CLA before. I don't know why my commits are associated with my old username `nicogeburek`. Can we merge anyway?

**Comment by MichaelCzcz** [comment]
@nicoschoenteich It seems that you have not updated your email address in your git settings. It still says nico.geburek@...
I can merge it, but please update your settings.

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Please update the tags of sapui5-fiori-cf-create-project. The name space "products" was deprecated over a year ago.

**Comment by nicoschoenteich** [comment]
Hi @MichaelCzcz, done.

**Comment by MichaelCzcz** [comment]
@nicoschoenteich I will merge it now, but please do not forget to update your email address in you local git settings.

**Pull request merged**
