### PR TITLE
Updating tutorial with new naming conventions

### PR DESCRIPTION
**Pull request by AriannaMussoBarcucci**
Updating the naming conventions: SAP launchpad Service --> SAP Build Work Zone, standard edition. Names updated in the tutorial and one screenshot changed.

### CODE REVIEW

**Comment by MichaelCzcz** [comment]
@AriannaMussoBarcucci Please resolve conflicts. To prevent conflicts always sync your fork at least once per day and pull all possible changes in you fork and the Tutorials-Contribution repos from Github before pushing any changes.

**Comment by AriannaMussoBarcucci** [comment]
@MichaelCzcz I did pull requests on my fork before pushing the changes. No conflicts appear in my VS Code and in Github the 'resolve conflicts' button is greyed out with message "These conflicts are too complex to resolve in web editor". Do you have any idea how else to resolve the conflicts? Or where they should appear in VS Code? Thanks!

**Comment by MichaelCzcz** [comment]
Creating a pull request is not the same as doing a pull from Github. Other authors are making changes to their their tutorials an therefore to the Tutorials repo that is the basis of your fork. Therefore you have to pull all changes from Github first before pushing your changes to Github. This has to be done for Tutorials and Tutorials-Contribution.

**Comment by AriannaMussoBarcucci** [comment]
Sorry, I meant I did a pull in github before pushing the changes. Any idea why I do not see any conflicts on my side in VS Code?

**Comment by MichaelCzcz** [comment]
When you are pushing your changes to production you are actually pushing them to your fork. So, the conflicts are in your fork in Github. From my personal experience, sometimes you have to pull several times before you get all the changes from GIthub in your local copy of the repository. 
Manually syncing your fork directly in Github before pulling can also be necessary. Since there are too many conflicts, the easiest way for you to solve this would be making a backup of your changes, closing your pull request, syncing your fork in Github, pulling your fork from Github (do it two or three times, just to be sure), re-applying the changes and following the instructions for publishing.

**Comment by AriannaMussoBarcucci** [comment]
Ok, I will try, thanks! My team just asked me to add a last-minute change anyway, so I would have had to create a new pull request regardless :)

**Comment by MichaelCzcz** [comment]
> Ok, I will try, thanks! My team just asked me to add a last-minute change anyway, so I would have had to create a new pull request regardless :)

Actually, you wouldn't. As long as your current pull request has not been merged or closed, you can add more changes.

**Pull request closed without merging**
