### PR TITLE
Initial Push of ABAP-ENV-IPS tutorial to production

### PR DESCRIPTION
**Pull request by Liebherr**

### CODE REVIEW

**Comment by Liebherr** [comment]
hm, somehow most of the tutorial stuff is missing :(

**Comment by MichaelCzcz** [comment]
> hm, somehow most of the tutorial stuff is missing :(

Can you please provide more information on what is missing and where it is missing?

**Comment by Liebherr** [comment]
Hi Michael,
well at the very beginning I only provided the tutorial parts for downloadable files within abap-env-ips for testing possibilities.
Meanwhile I moved the tutorial to abap-environment-ips and that move looked ok on QA. But the Push to Prod somehow did not contain that new folder, so that in my fork there's still only the old folder with the two files :(
Do I need to adapt my fork manually now?
Thanks and Regards
Ulrike

**Comment by Liebherr** [comment]
obsolete folder not to be pushed to prod

**Pull request closed without merging**
