### PR TITLE
Tour the SAP Community 2022 tutorial 

### PR DESCRIPTION
**Pull request by lenastodal**
rule change

### CODE REVIEW

**Comment by MichaelCzcz** [comment]
The rules file is global for QA and production. There is no need for a pull request if you just update the rules file.

**Comment by lenastodal** [comment]
﻿Hi Michael,

Right, I wasn’t aware of that. Meaning, only when I change the md file, I need to submit a pull request?
So the rule is now “live”?

Thank you,
Lena

From: Michael Czadankiewicz ***@***.***>
Reply to: sap-tutorials/Tutorials ***@***.***>
Date: Friday, 8. July 2022 at 09:13
To: sap-tutorials/Tutorials ***@***.***>
Cc: "Stodal, Lena" ***@***.***>, Author ***@***.***>
Subject: Re: [sap-tutorials/Tutorials] Tour the SAP Community 2022 tutorial (PR #18600)


The rules file is global for QA and production. There is no need for a pull request if you just update the rules file.

**Comment by MichaelCzcz** [comment]
A pull request is only necessary when you make changes to the md-file and images. So, yes, it is live.

**Comment by lenastodal** [comment]
Hi Michael,

I wanted to briefly reach out and check with you on the below:
I changed the rule file and added “Swift Solver III|Swift Solver 3” to line 10.

***@***.***

I checked on the rule in the tutorial itself: https://developers.sap.com/tutorials/community-2022.html, but it seems to be incorrect:

***@***.***
***@***.***


I pushed it to QA, because (in case I understood you correctly last time), I don’t need to push it to PROD and create a pull request, right?

Thank you,
Lena

From: "Stodal, Lena" ***@***.***>
Date: Friday, 8. July 2022 at 09:14
To: Michael Czadankiewicz ***@***.***>
Cc: Author ***@***.***>, sap-tutorials/Tutorials ***@***.***>, sap-tutorials/Tutorials ***@***.***>
Subject: Re: [sap-tutorials/Tutorials] Tour the SAP Community 2022 tutorial (PR #18600)

Hi Michael,
Right, I wasn’t aware of that. Meaning, only when I change the md file, I need to submit a pull request?
So the rule is now “live”?

Thank you,
Lena

From: Michael Czadankiewicz ***@***.***>
Reply to: sap-tutorials/Tutorials ***@***.***>
Date: Friday, 8. July 2022 at 09:13
To: sap-tutorials/Tutorials ***@***.***>
Cc: "Stodal, Lena" ***@***.***>, Author ***@***.***>
Subject: Re: [sap-tutorials/Tutorials] Tour the SAP Community 2022 tutorial (PR #18600)


The rules file is global for QA and production. There is no need for a pull request if you just update the rules file.

**Comment by lenastodal** [comment]
Sorry, I didn’t know that. Thanks!

From: Michael Czadankiewicz ***@***.***>
Reply to: sap-tutorials/Tutorials ***@***.***>
Date: Friday, 8. July 2022 at 09:38
To: sap-tutorials/Tutorials ***@***.***>
Cc: "Stodal, Lena" ***@***.***>, Author ***@***.***>
Subject: Re: [sap-tutorials/Tutorials] Tour the SAP Community 2022 tutorial (PR #18600)


A pull request is only necessary when you make changes to the md-file and images. So, yes, it is live.

**Pull request closed without merging**
