### PR TITLE
Prerequisites

### PR DESCRIPTION
**Pull request by AnnikaGonnermann**
specified prerequisites with more info on trial vs free tier

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Please update the tag name spaces (products -> software-product) Thank you.

**Comment by AnnikaGonnermann** [comment]
@MichaelCzcz  Done ✅

**Comment by MichaelCzcz** [comment]
> @MichaelCzcz Done ✅

I don't see the commit.

**Comment by AnnikaGonnermann** [comment]
Hey @MichaelCzcz I pushed again, plz check
Thanks!

**Pull request merged**
