### PR TITLE
Updated for new features 

### PR DESCRIPTION
**Pull request by ArchanaShukla**

### CODE REVIEW

**Comment by MichaelCzcz** [comment]
@ArchanaShukla Please resolve the conflicts. Thank you.

**Comment by MichaelCzcz** [comment]
> Hello @MichaelCzcz, I don't have the write access to Resolve the Conflicts. Please help!

In Atom, please do a pull, then resolve the conflicts and then push again.

**Comment by ArchanaShukla** [comment]
I have pulled the changes and pushed again. Please check!

**Comment by MichaelCzcz** [comment]
> I have pulled the changes and pushed again. Please check!

Did you also resolve the conflicts?

**Comment by ArchanaShukla** [comment]
Will re-submit again

**Pull request closed without merging**
