### PR TITLE
Automatic commit: Move 'cp-webanalytics-setup' from QA to Production

### PR DESCRIPTION
**Pull request by Vikramkulkarni01**
Trial details have been updated to the Free tier.

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Please update tags (products -> software-product)

**Comment by Vikramkulkarni01** [comment]
> 

Hi @MichaelCzcz , 
I updated the tags and tried pushing to prod again. Please check and merge it.

**Comment by MichaelCzcz** [comment]
You were not supposed to add another tag, but to replace products with software-product in existing tags. ;-)

**Comment by Vikramkulkarni01** [comment]
I understood now. Updates as per your recommendation

**Pull request merged**
