### PR TITLE
Updating Azure Tutorial

### PR DESCRIPTION
**Pull request by DevelopedByAnurag**
Incorporating a few suggested changes to azure tutorial.

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Please fix spelling. Put terms in back-ticks if they are spelled correctly.

CHECK SPELLING:
  
  >Error:
      file: ai-core-azure.md
      line: 29
      reason: NoSQL

  >Error:
      file: ai-core-azure.md
      line: 35
      reason: config

  >Error:
      file: ai-core-azure.md
      line: 49
      reason: config

**Comment by DevelopedByAnurag** [comment]
> back-ticks

Hi @MichaelCzcz I Confirm the the above spellings are spelled correct !

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Again: Put those terms in back-ticks if they are spelled correctly.

**Comment by DevelopedByAnurag** [comment]
> Again: Put those terms in back-ticks if they are spelled correctly.

Hi @MichaelCzcz I have kept those terms in the back-ticks can you now pls approve the PR ?

**Pull request merged**
