### PR TITLE
Updated for screen changes

### PR DESCRIPTION
**Pull request by ArchanaShukla**

### CODE REVIEW

**Comment by jmmargo** [comment]
Please resolve the conflicts.

**Comment by ArchanaShukla** [comment]
Hello @jmmargo , 
I could not see the conflicts, the one I committed have to be taken. Please help me to resolve the conflicts as Atom does not show the conflicts

**Comment by MichaelCzcz** [comment]
@ArchanaShukla Please follow these steps:
image

**Comment by ArchanaShukla** [comment]
Done, merged the conflicts. Please approve!

**Pull request merged**
