### PR TITLE
Trial Update

### PR DESCRIPTION
**Pull request by Karunaharan**
Revising the documentation to cover the latest changes owing to the new iStudio.

### CODE REVIEW

**Comment by MichaelCzcz** [comment]
@Karunaharan Please resolve the conflicts. Thank you.

**Comment by Karunaharan** [comment]
hi @MichaelCzcz - I have identified the conflict. But how do I resolve it? Should I make the changes and create another pull request? Please let me know the next steps.

**Comment by Karunaharan** [comment]
Hi @MichaelCzcz I have resolved the conflict. Please merge the changes.

**Comment by Karunaharan** [comment]
Hello @MichaelCzcz - I'm ok with the changes that you proposed. How do I accept them?

**Comment by MichaelCzcz** [comment]
> Hello @MichaelCzcz - I'm ok with the changes that you proposed. How do I accept them?

Please make the change in Atom and push again.

**Pull request merged**
