### PR TITLE
Update fiori-tools-rap-create-application.md

### PR DESCRIPTION
**Pull request by carwelsh**

### CODE REVIEW

**Comment by MichaelCzcz** [comment]
@carwelsh Are you a SAP employee? You don't seem to be a member of the tutorial authors' group.

**Comment by carwelsh** [comment]
@MichaelCzcz Hi , yes I am. My I number is I058007.

**Comment by MichaelCzcz** [comment]
@carwelsh Please do not post your SAP user name in public!
Please complete the tutorial author onboarding process: https://jam4.sapjam.com/groups/A7NmsKmoG9vVaxizKhdQOk/overview_page/jpJF7KXn5B2tFFQVOQ1Ybm?edit_mode=true

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Please update the tags. The name space "products" is no longer valid. Please change it to "software-product".

**Comment by carwelsh** [comment]
@MichaelCzcz - Apologies I thought I was on the internal Github where it is already visible. I was wondering why you were asking

**Comment by MichaelCzcz** [comment]
> @MichaelCzcz - Apologies I thought I was on the internal Github where it is already visible. I was wondering why you were asking

I am asking because your profile doesn't meet the requirements for tutorial authors, it doesn't even have your full name. And since somebody else is listed as the tutorial's owner and basically only tutorial owners are allowed to make changes to their tutorials, I have to ask.

**Pull request closed without merging**
