### PR TITLE
Automatic commit: Move 'fiori-tools-mockserver-opa' from QA to Produc…

### PR DESCRIPTION
**Pull request by reginasheynblat**
…tion
Updated Screens  and changed links for Open Source Mock server

### CODE REVIEW

**Comment by MichaelCzcz** [comment]
@reginasheynblat Plesae resolve conflicts. Thank you.

**Comment by reginasheynblat** [comment]
@MichaelCzcz  I just uploaded new screenshots that used the same name and everything.. I am not sure why there are conflicts.

**Comment by MichaelCzcz** [comment]
> @MichaelCzcz I just uploaded new screenshots that used the same name and everything.. I am not sure why there are conflicts.

It looks like you did something else, because this PR looks as if it was for a completely new tutorial. All the files should have an orange marker, not a green one. Please pull and push again.

**Comment by reginasheynblat** [comment]
@MichaelCzcz  i created a new pr but it pulled in the md. file also.. I am not sure why its doing that.

**Pull request closed without merging**
