### PR TITLE
Update ai-core-and-LP-provisioning-GA.md

### PR DESCRIPTION
**Pull request by helenaaaaaaaaaa**

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Upper case letters are not allowed in file names. Please change them to lower case.

**Comment by MichaelCzcz** [comment]
@helenaaaaaaaaaa unfortunately there are more issues that need to be fixed:

CHECK SPELLING:
  
  >Error:
      file: ai-core-and-LP-provisioning-GA.md
      line: 36
      reason: SLAs

  >>> 1 File(s) checked with 1 Error(s)

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
 

CHECK CONTENT:
  
  >Error:
      file: ai-core-and-LP-provisioning-GA.md
      line: 105
      reason: missing image -> ReviewAndCreateLP.png

**Comment by helenaaaaaaaaaa** [comment]
I have made the requested changes

**Comment by MichaelCzcz** [comment]
@helenaaaaaaaaaa in this PR there is a second tutorial now. Did you want to publish this one too?
image

**Comment by helenaaaaaaaaaa** [comment]
I renamed it because of the lower cases so it should just be one, with the lower case name. The content is the same.


H
________________________________

**Pull request merged**
