### PR TITLE
Update fiori-tools-cap-modify-object-page

### PR DESCRIPTION
**Pull request by cjbernal**
Updated fiori-tools-cap-modify-object-page to reflect new procedure for enabling flexible column layout

### CODE REVIEW

**Comment by cjbernal** [comment]
Hi tutorials team, it looks like this PR also copied over a failed commit from last week: https://github.com/sap-tutorials/Tutorials/pull/20851/commits/37443c1e858e1455f18ec0d8095ed83b505d72ec

This was actually handled already via this PR: https://github.com/sap-tutorials/Tutorials/pull/20847#event-8178753060

Please let me know if you need anything from my side. Otherwise, if it simply duplicates the changes and is harmless, please feel free to merge.

**Comment by MichaelCzcz** [comment]
You could check in "Files changes" if you can see the changes from that commit. If they are part of this pull request, simply revert them and push again.

**Comment by cjbernal** [comment]
Sorry Michael, I'm not as familiar with GitHub PRs and reversion as some of my developer colleagues. From the VSC extension, I can revert the last change -- which reverted the change to fiori-tools-cap-modify-object-page. This is the change I'd actually like to make, but I understand why that occurred. This can easily be recommitted. 

If I go to revert last commit again, I get a warning that this will revert a merge commit but it does not mention which one. Is there a more visual way to do this? I don't see options for commit reversion in the browser version of GitHub.

**Comment by MichaelCzcz** [comment]
You can simply undo the changes locally within the respective files and push again. If you want to apply these changes at a later point, make a backup.

**Comment by cjbernal** [comment]
Thanks @MichaelCzcz. Here's the curious part, though -- those are changes I wanted but already made (and live) so I don't necessarily want to revert them. I'm not sure how they ended up in this PR. For example, here's the production tutorial: https://developers.sap.com/tutorials/fiori-tools-generate-project.html

Search for `list report page`. You'll find that it already reads `list report page` as in the changes, rather than the old `list report object page` .

Any tips? Or still revert them?

**Comment by MichaelCzcz** [comment]
If you have already applied those changes earlier, you should do a fetch + pull (for both tutorials and Tutorials-Contribution) and push again and they should be automatically removed from your pull request.

**Comment by cjbernal** [comment]
Thanks @MichaelCzcz. I have done as instructed: fetch + pull and push for both tutorials and tutorials-contribution. Everything is shown as up-to-date. Can you safely merge here or do I need to open a new PR?

**Pull request merged**
